### PR TITLE
#47 Integration tests

### PR DESCRIPTION
**Pull request by Suban05**
## Changes
* Added gem Capybara
* Added the `start_as_tester` and `tester_human` methods to `test__helper`. They are needed to log in to the application as a tester using fake-login on the main page. In the `start_as_tester` method, all user tokens are deactivated, because sometimes an error occurred with exceeding the limit of active tokens
* Added tests for most scenarios of user interaction with the application

### CODE REVIEW

**Comment by 0crat** [comment]
@Suban05 It is [not a good idea](https://www.yegor256.com/2014/04/15/github-guidelines.html) to name Git branches the way you named this one: "`integration-tests`". You've earned -10 points. Next time, better give your branch the same name as the number of the ticket that you are solving. In this case, a perfect name, for example, would be "`137`". Your running balance is +55.

**Review by yegor256 — APPROVED** [review]
@Suban05 looks very good, thanks!

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@Suban05 Thanks for the contribution! You've earned +5 points for this: +20 as a basis; +5 for 732 hits-of-code; -7 for too many hits-of-code (732 >= 100); -15 for way too many hits-of-code (732 >= 400); -5 for 3 comments of reviewers; +7 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is +45.

**Comment by 0crat** [comment]
@yegor256 Thanks for the review! You've earned +70 points for this: +25 as a basis; +40 for 732 hits-of-code; +5 for 4 comments.  Your running balance is -370.

**Pull request merged**
