### PR TITLE
#167 The `lock` method does not exist in `jobs.rb`

### LINKED ISSUE #167: The `lock` method does not exist in `jobs.rb`
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L111

I suggest that it is a typo and we should write: `the_human.locks.lock(params[:owner]) unless params[:owner].nil? `

### PR DESCRIPTION
**Pull request by Suban05**
## Changes

* Moved a `name` variable up
* Added call `the_human.locks.lock` instead of `the_human.jobs.lock`
* Added a test

Fixes #167

### CODE REVIEW

**Comment by Suban05** [comment]
@yegor256 `bundle update` doesn't work

**Comment by Suban05** [comment]
@yegor256 ready to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@Suban05 Thanks for the contribution! You've earned +10 points for this: +25 as a basis; -15 for the lack of code review. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+258](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
