### PR TITLE
enables rack deflater middleware

### LINKED ISSUE #115: `pull` must return zipped content if `Accept` is set for it
Let's make `/pull` (from `front_push.rb`) to return zipped content, if `Accept` header is set for it.

### PR DESCRIPTION
**Pull request by tank-bohr**
fixes #115
related to https://github.com/yegor256/judges/issues/84
see also https://github.com/zerocracy/baza.rb/pull/13

### CODE REVIEW

**Comment by tank-bohr** [comment]
@yegor256, maybe you can take a look, as it is a very tiny change

**Comment by yegor256** [comment]
@tank-bohr is it possible to add a test, which would fail without this line?

**Comment by tank-bohr** [comment]
@yegor256 yes. I've just added one

**Comment by yegor256** [comment]
@tank-bohr thanks!

**Comment by yegor256** [comment]
@tank-bohr released

**Comment by 0crat** [comment]
@tank-bohr Great job on your contribution! 🌟 You've earned +5 points, bringing your total to [+111](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). While we'd love to see more code reviews and comments next time, your effort is appreciated. [Keep the momentum going](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) and continue to enhance our project!

**Pull request merged**
