### PR TITLE
#168 incorrect call of `locks.lock()` in `front_push`

### LINKED ISSUE #168: incorrect call of `locks.lock()` in `front_push`
The parameter `name` is missing.

https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L145
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L155
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L165
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L172
https://github.com/zerocracy/baza/blob/273b42d6edcaf0e435e5a0523f2d781dd0a45d88/front/front_push.rb#L186

### PR DESCRIPTION
**Pull request by Suban05**
## Changes

* Added a job name parameter when calling `locks.lock`
* Added tests

Fixes #168

### CODE REVIEW

**Comment by Suban05** [comment]
@Yegorov can you review it, please?

**Review by Yegorov — APPROVED** [review]
@Suban05 looks fine!

**Comment by Suban05** [comment]
@yegor256 can you merge it?

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@Suban05 Hey there, awesome job on your contribution! 🎉 You've racked up +29 points: 25 for the base, and a sweet 9 points for your 197 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html). We did have to deduct 5 points due to the low comment count (only 4), but don't sweat it! Remember, more comments can boost your score next time. Keep the code coming and aim for that 80-point max! Your current balance is [+268](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's see you hit that 800 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) milestone soon – just watch out for that 15-point deduction! 😉 [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the great work!

**Comment by 0crat** [comment]
@Yegorov Hey there! 👋 Great job on the review! You've snagged +20 points for this one. Here's the breakdown: +25 as the base reward, -10 because there were fewer than 6 comments, but you got +5 back for the 5 comments you did make. Every comment counts! 💪 Remember, more comments could boost your points even higher next time. Your current balance is sitting pretty at [+111](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the awesome work!

**Pull request merged**
