### PR TITLE
#156 fix `lock.ip` column is missing

### LINKED ISSUE #156: `lock.ip` column is missing
Let's add `ip` column to the `lock` table and then record the IP of the requestor of every lock. Let's show the IP in the `locks.haml` view.

### PR DESCRIPTION
**Pull request by Suban05**
Fixes #156

### CODE REVIEW

**Review by Yegorov — APPROVED** [review]
@Suban05 looks fine!

**Comment by yegor256** [comment]
@Suban05 thanks!

**Comment by 0crat** [comment]
@Yegorov Great job on the review! 🌟 You've earned +4 points: +4 base, -10 for minimal comments, but +10 to recognize your effort. Your balance now stands at [+435](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for more detailed feedback next time!

**Comment by 0crat** [comment]
@Suban05 Great contribution! Here's your reward breakdown: +4 base points, +0.05 for each hit-of-code (capped at 16), -4 for few comments (only 1), and adjusted to ensure a minimum of 4 points. Your total: +4 points. Remember, more [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) and encouraging more review comments can boost your future rewards. [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the good work! Your current balance: [+569](https://zerocracy.github.io/judges-action/zerocracy-vitals.html).

**Pull request merged**
